### PR TITLE
Homework V (HW5)

### PR DESCRIPTION
**Pull request by vitreusx**

### CODE REVIEW

**Comment by hbaniecki** [comment]
looks great! 

since this PR has files from HW4, we can merge this after https://github.com/mim-uw/eXplainableMachineLearning-2023/pull/100 is resolved

**Comment by hbaniecki** [comment]
homework is already graded, we can merge it if you resolve conflicts

**Comment by hbaniecki** [comment]
@vitreusx homework is already graded, we can merge it if you resolve conflicts, or close the PR

**Comment by vitreusx** [comment]
@hbaniecki I've resolved the conflicts, you should be able to merge.

**Pull request merged**
