### PR TITLE
HW2 Krystian Krol

### PR DESCRIPTION
**Pull request by Krystian-Krol**
- Added introduction to HW1 as per comment on pull request
- Added HW2 notebook and html without the code

### CODE REVIEW

**Comment by hbaniecki** [comment]
image

**Comment by Krystian-Krol** [comment]
- Moved everything to single folder 
- Changed notebook to have the appendix and 0 code for main part
- Removed unnecessary parts from html file

**Comment by hbaniecki** [comment]
@Krystian-Krol Linear regression is a regressive model, whereas you are performing classification. This should be Logistic Regression and prediction made with `predict_proba()` instead of `predict()`.

**Comment by Krystian-Krol** [comment]
- Changed linear regression to Logistic Regression

**Pull request merged**
