### PR TITLE
Hw2 Paweł Pawlik

### PR DESCRIPTION
**Pull request by PaPa3**

### CODE REVIEW

**Comment by hbaniecki** [comment]
This homework seems chaotic:
1. Fix math rendering
2. The code is invoked from bottom to top, the code cells at the top are not required
3. Fix comparison with dalex (there are no plots)

Insert proper images, please

**Comment by PaPa3** [comment]
I fixed 1, 2, 3,

I have a question about 2:
This was done this way to only insert images at the proper position, i.e. near the written description about them. The code was just one liner execution of the function which for me does not decrease readability of the first half of the notebook (but of course violates strict no python code policy). Now with this removed, the images are only in the appendix, which for me is less readable compared to images next to the corresponding text. Is current formatting good?

**Comment by hbaniecki** [comment]
> This was done this way to only insert images at the proper position, i.e. near the written description about them. The code was just one liner execution of the function which for me does not decrease readability of the first half of the notebook (but of course violates strict no python code policy).

This would be fine but the `dalex` plots were not shown in the report.

>  Now with this removed, the images are only in the appendix, which for me is less readable compared to images next to the corresponding text. Is current formatting good?

I agree, it is less readable. It is not good, because the images should be in the report part.

**Comment by PaPa3** [comment]
Ok, thank you for your response! 
I restored the plots in the first half of the notebook (`dalex` plots are now rendered correctly). Let me know if there is something that still requires correction.

**Comment by hbaniecki** [comment]
"dalex plots are now rendered correctly" 
image

I hope it will work next time

**Pull request merged**
