### PR TITLE
Szymon Antoniak hw1 + hw2 + hw3

### PR DESCRIPTION
**Pull request by Simontwice**

### CODE REVIEW

**Comment by pbiecek** [comment]
good direction
+add comments related to final results, maybe compare ROC curves

**Comment by Simontwice** [comment]
OK done!

SA

pt., 14 paź 2022 o 13:34 Przemysław Biecek ***@***.***>
napisał(a):

**Comment by pbiecek** [comment]
@Simontwice 
HW2 shall be in a different folder and in a separate pull request

HW1 is ok

**Comment by hbaniecki** [comment]
HW2 is ok, but next time please make it executable (now the first cell returns an error) and export the plots/add screenshots to the report if needed.

Separate PR is not needed, but folders/directories needs to be fixed

**Comment by Simontwice** [comment]
I will create separate PRs for all 3 HWs to date.

**Comment by hbaniecki** [comment]
HW3 violates the following 
image

**Pull request merged**
