### PR TITLE
HW3 + HW4 + HW5 + HW6

### PR DESCRIPTION
**Pull request by MaciejWojtala**

### CODE REVIEW

**Comment by pbiecek** [comment]
which players are explained in these examples?
please add critical comments on whether the model/explanation works well/badly/as expected.

**Comment by MaciejWojtala** [comment]
HW4

**Comment by MaciejWojtala** [comment]
HW5

**Comment by MaciejWojtala** [comment]
HW6

**Comment by pbiecek** [comment]
@MaciejWojtala WH4 is ok

**Comment by pbiecek** [comment]
@MaciejWojtala WH6 first part is wrong, please fix and upload fixed solution

**Comment by MaciejWojtala** [comment]
I've uploaded fixed solution to Task 1 from HW 6

**Comment by pbiecek** [comment]
HW6 is ok

**Comment by pbiecek** [comment]
HW3 is ok

**Comment by hbaniecki** [comment]
HW 5 looks good.

**Pull request merged**
