### PR TITLE
Jk hmw 6

### PR DESCRIPTION
**Pull request by kuba-krj**

### CODE REVIEW

**Comment by pbiecek** [comment]
move results to right directory

**Comment by kuba-krj** [comment]
Sorry, I changed the directory

**Comment by pbiecek** [comment]
@kuba-krj there is an conflict in `Homeworks/HW6/README.md`
you should not modify this file to avoid conflict, please correct

**Comment by kuba-krj** [comment]
Sorry, the issue with README is fixed now

**Pull request merged**
