### PR TITLE
Maciej Domaradzki HW3 + HW4 + HW5 + HW6 

### PR DESCRIPTION
**Pull request by DomaradzkiMaciej**

### CODE REVIEW

**Comment by pbiecek** [comment]
please be more precise in your descriptions.
There are now one-two sentences and a few diagrams.
But which figure with which to compare?
What are the conclusions, from what do they derive?

**Comment by DomaradzkiMaciej** [comment]
I added homework 4 & 5 and fixed homework 3.

**Comment by DomaradzkiMaciej** [comment]
I added homework 6.

**Comment by hbaniecki** [comment]
HW5 has like bare minimum descriptions

**Comment by pbiecek** [comment]
@DomaradzkiMaciej HW4 first task is ok, second task should has more comments that summarise what is visible in attached plots

**Comment by pbiecek** [comment]
@DomaradzkiMaciej HW6 second task is ok, first task lacks of detailed descriptions how these results were calculated

**Comment by DomaradzkiMaciej** [comment]
@pbiecek I fixed HW4, HW5 and HW6.

**Comment by pbiecek** [comment]
WH4: 75%
WH6: 75%
in both cases comments are very scarce

**Comment by hbaniecki** [comment]
HW5: comments do not compare different measures of variable importance -25%

**Pull request merged**
