### PR TITLE
hw1 kajetan husiatynski

### PR DESCRIPTION
**Pull request by Kejmer**

### CODE REVIEW

**Comment by hbaniecki** [comment]
+add title
+add sections to make the report more readable
+add comments to each trained model
+summary of models, maybe with ROC curves

**Comment by Kejmer** [comment]
Hey I've changed the model, but didn't used the ROC curve since I switched my approach to only regression models.

**Comment by hbaniecki** [comment]
Hi, what do you mean by "accuracy" when evaluating regression models?

**Comment by Kejmer** [comment]
Hi, I think that's a mistake that I did after switching from classifiers to regression models. Here it's obviously R2 score.

**Comment by hbaniecki** [comment]
Please correct this (occurs 9 times).

**Comment by Kejmer** [comment]
@hbaniecki I've corrected my error

**Comment by hbaniecki** [comment]
thanks

**Pull request merged**
