### PR TITLE
HW1 + HW2 + HW3+HW4+HW5+HW6 Jacek Rutkowski HB

### PR DESCRIPTION
**Pull request by jacek-tomasz-rutkowski**

### CODE REVIEW

**Comment by hbaniecki** [comment]
+add title and section titles
+add comments to each analysis step
+extend: add data analysis and/or residual analysis

**Comment by hbaniecki** [comment]
@jacek-tomasz-rutkowski files are in the wrong directory (HW1?)
image

**Comment by jacek-tomasz-rutkowski** [comment]
Tak, dlatego pytałem po zajęciach, czy doszło, bo coś mi nie wychodziło, jak próbowałem dodać do HW2.

**Comment by hbaniecki** [comment]
`Homeworks/HW2/HB_HW_2_part_1_JR.ipynb` Has no plots (?)

**Comment by pbiecek** [comment]
@jacek-tomasz-rutkowski HW4 - first part is ok, second part - missing plots and descriptions in https://github.com/jacek-tomasz-rutkowski/eXplainableMachineLearning-2023/blob/main/Homeworks/HW4/JacekRutkowski/XAI_HW_4__results.ipynb

**Comment by pbiecek** [comment]
@jacek-tomasz-rutkowski HW6 missing plots and numerical results

https://htmlpreview.github.io/?https://raw.githubusercontent.com/jacek-tomasz-rutkowski/eXplainableMachineLearning-2023/main/Homeworks/HW6/JacekRutkowski/XAI_HW_6_results.html

**Comment by pbiecek** [comment]
HW4 - ok, but comments are quite limited, especially in the last task (first part is ok)

**Comment by pbiecek** [comment]
HW6: second part ok
in the first part the last metric is wrong (see solutions presented by other students, this ratio shall be higher than 1.7)

**Comment by pbiecek** [comment]
HW3: 50%
- late submission (one week after deadline)
- very limited comments

**Comment by pbiecek** [comment]
HW2: 50%
- wrong folder
- strange results for SHAP - but there is absolutely no comment on what is happening and why these results are so strange. Is it a problem with model or explanations?

**Comment by pbiecek** [comment]
HW1 is ok, but two weeks after deadline

**Comment by hbaniecki** [comment]
HW5: visualization of shap importance has misleading title and wrong x-axis title (dropout loss) -25%

**Pull request merged**
