### PR TITLE
[HW2] [HB] Kajetan Husiatynski

### PR DESCRIPTION
**Pull request by Kejmer**

### CODE REVIEW

**Comment by hbaniecki** [comment]
can't see any plots 
image

**Comment by Kejmer** [comment]
@hbaniecki I've pushed the plots to the repository now

**Comment by hbaniecki** [comment]
I don't understand the last part. You seem not to use these models.

image

**Comment by Kejmer** [comment]
Oh, this is paragraph from homework 1 that i've already deleted. I think I forgot about it.

**Comment by hbaniecki** [comment]
ok

**Pull request merged**
