### PR TITLE
Jk hm5 (HW5)

### PR DESCRIPTION
**Pull request by kuba-krj**

### CODE REVIEW

**Comment by hbaniecki** [comment]
error in the report, shap plot looks like copied from the repository

**Comment by hbaniecki** [comment]
why is there an error in the report?

**Comment by kuba-krj** [comment]
The reason for error was that I removed 'heart.csv' from the folder instead of adding it to .gitignore and then executed last cell of notebook. It's fixed now  (I executed the cell with 'heart.csv' in the folder). Also added html version. Sorry for the mistake

**Comment by hbaniecki** [comment]
@kuba-krj looks ok, homework is already graded, we can merge it if you resolve conflicts, or close the PR

**Pull request closed without merging**
